// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using benefits.Models;

namespace benefits.Migrations
{
    [DbContext(typeof(TablesDbContext))]
    [Migration("20201022141454_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("benefits.Models.Benefits", b =>
                {
                    b.Property<int>("benefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("benefitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("policyId")
                        .HasColumnType("int");

                    b.HasKey("benefitId");

                    b.HasIndex("policyId");

                    b.ToTable("benefit");
                });

            modelBuilder.Entity("benefits.Models.Groups", b =>
                {
                    b.Property<int>("groupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("groupDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("groupId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("benefits.Models.Policies", b =>
                {
                    b.Property<int>("policyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("policyDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("policyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("policyId");

                    b.HasIndex("groupId");

                    b.ToTable("policy");
                });

            modelBuilder.Entity("benefits.Models.Benefits", b =>
                {
                    b.HasOne("benefits.Models.Policies", "Policy")
                        .WithMany("benefits")
                        .HasForeignKey("policyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("benefits.Models.Policies", b =>
                {
                    b.HasOne("benefits.Models.Groups", "Group")
                        .WithMany("policies")
                        .HasForeignKey("groupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
